{
  "id": "topic_5399888",
  "title": "solayagim",
  "author": "solayagim",
  "created_time": "May 23, 2022, 07:21:49 PM",
  "content": "I have installed global electrumx server, its up and running. Getting blocks from coin daemon. Configuration files are below. Somehow local electrum wallet does not connect to the server and i could not find anyone who reproduce the same error. I couldn't determine if the problem is with the local wallet or the server.Need advise please.Wallet: https://github.com/koraycoding/electrum-wdcelectrumx.conf:Code:COIN = WorldcoinDB_DIRECTORY = /home/koray/electrumx_dbDAEMON_URL = worldcoin:worldcoin@ubuntu:11082SERVICES = tcp://:50001,ssl://electrum.mydomain.biz:50002,rpc://142.132.237.8:11082EVENT_LOOP_POLICY = uvloopMAX_SESSIONS = 500INITIAL_CONCURRENT = 50COST_SOFT_LIMIT = 0COST_HARD_LIMIT = 0DONATION_ADDRESS = WU9eqGsiheuTG59mUhcksifzWzexRaDBPsSSL_CERTFILE = /home/koray/electrumx/ssl/public.crtSSL_KEYFILE = /home/koray/electrumx/ssl/private.keyelectrumx.service:Code:[Unit]Description=ElectrumxAfter=network.target[Service]EnvironmentFile=/etc/electrumx.confExecStart=/home/koray/electrumx/electrumx_serverUser=korayLimitNOFILE=8192TimeoutStopSec=30min[Install]WantedBy=multi-user.targetworldcoin.conf:Code:listen=1server=1txindex=1rpcuser=worldcoinrpcpassword=worldcoinrpcallowip=0.0.0.0/0rpcbind=0.0.0.0addnode=....electrum wallet log:Code:20220523T143545.238410Z |     INFO | simple_config.SimpleConfig | electrum directory /home/koray/.electrum-wdc20220523T143545.240120Z |     INFO | logging | Electrum-WDC version: 4.2.1 - https://worldcoin.org - https://github.com/koraycoding/electrum-wdc20220523T143545.241905Z |     INFO | logging | Python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]. On platform: Linux-5.15.41-1-lts-x86_64-with-glibc2.3520220523T143545.242034Z |     INFO | logging | Logging to file: /home/koray/.electrum-wdc/logs/electrum_wdc_log_20220523T143545Z_16904.log20220523T143545.242120Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''20220523T143545.243017Z |     INFO | plugin.Plugins | registering hardware bitbox02: ('hardware', 'bitbox02', 'BitBox02')20220523T143545.243319Z |     INFO | plugin.Plugins | registering hardware coldcard: ('hardware', 'coldcard', 'Coldcard Wallet')20220523T143545.243806Z |     INFO | plugin.Plugins | registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')20220523T143545.245657Z |     INFO | plugin.Plugins | registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')20220523T143545.246116Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')20220523T143545.246585Z |     INFO | plugin.Plugins | registering hardware safe_t: ('hardware', 'safe_t', 'Safe-T mini wallet')20220523T143545.246857Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')20220523T143545.247125Z |     INFO | plugin.Plugins | registering wallet type ('2fa', 'trustedcoin')20220523T143545.247644Z |    DEBUG | util.profiler | Plugins.__init__ 0.005320220523T143545.247936Z |     INFO | network | blockchains [0]20220523T143545.248268Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko20220523T143545.248760Z |    DEBUG | util.profiler | Daemon.__init__ 0.001020220523T143545.248873Z |     INFO | daemon.Daemon | launching GUI: qt20220523T143545.249441Z |     INFO | network | starting network20220523T143545.249749Z |     INFO | network | setting proxy None20220523T143545.250180Z |     INFO | daemon.Daemon | starting taskgroup.20220523T143545.250692Z |     INFO | network | connecting to electrum.mydomain.biz:50002:s as new interface20220523T143545.252178Z |     INFO | network | starting taskgroup (0x7fd672b33040).20220523T143545.252634Z |     INFO | daemon.CommandsServer | now running and listening. socktype=unix, addr=/home/koray/.electrum-wdc/daemon_rpc_socket20220523T143545.253437Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for USD20220523T143545.308519Z |     INFO | gui.qt.history_list | could not import electrum_wdc.plot. This feature needs matplotlib to be installed.20220523T143545.410602Z |     INFO | gui.qt.ElectrumGui | Qt GUI starting up... Qt=5.15.2, PyQt=5.15.620220523T143545.547121Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.137920220523T143545.547777Z |     INFO | storage.WalletStorage | wallet path /home/koray/.electrum-wdc/wallets/default20220523T143545.548543Z |    DEBUG | util.profiler | WalletDB._load_transactions 0.000320220523T143545.549297Z |    DEBUG | util.profiler | AddressSynchronizer.load_local_history 0.000020220523T143545.549506Z |    DEBUG | util.profiler | AddressSynchronizer.check_history 0.000120220523T143545.597410Z |    DEBUG | util.profiler | AddressList.update 0.000020220523T143545.640200Z |    DEBUG | util.profiler | Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.010320220523T143545.640381Z |    DEBUG | util.profiler | ElectrumWindow.load_wallet 0.025320220523T143545.641499Z |     INFO | gui.qt.ElectrumGui | starting Qt main loop20220523T143546.023607Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs20220523T143546.024335Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.000320220523T143546.024462Z |    DEBUG | util.profiler | HistoryModel.refresh 0.000920220523T143546.025486Z |    DEBUG | util.profiler | AddressList.update 0.000020220523T143550.684533Z |     INFO | interface.[electrum.mydomain.biz:50002] | succeeded in getting cert20220523T143550.694637Z |     INFO | exchange_rate.CoinGecko | received fx quotes20220523T143550.901152Z |     INFO | interface.[electrum.mydomain.biz:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']20220523T143550.959309Z |     INFO | interface.[electrum.mydomain.biz:50002] | set blockchain with height -120220523T143550.959945Z |     INFO | interface.[electrum.mydomain.biz:50002] | can't connect 724099120220523T143550.960421Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header 0 in mode backward20220523T143550.961407Z |     INFO | network | switching to electrum.mydomain.biz:50002:s20220523T143551.005078Z |     INFO | network | fee_estimates {}20220523T143551.020379Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header -7240991 in mode backward20220523T143551.036040Z |     INFO | network | fee_histogram []20220523T143551.103499Z |  WARNING | interface.[electrum.mydomain.biz:50002] | disconnecting due to RPCError(1, '-7240991 should be a non-negative integer')20220523T143551.104255Z |    DEBUG | interface.[electrum.mydomain.biz:50002] | (disconnect) trace for RPCError(1, '-7240991 should be a non-negative integer')Traceback (most recent call last):  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 498, in wrapper_func    return await func(self, *args, **kwargs)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 521, in run    await self.open_session(ssl_context)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 667, in open_session    async with self.taskgroup as group:  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/curio.py\", line 297, in __aexit__    await self.join()  File \"/home/koray/electrum-wdc/electrum_wdc/util.py\", line 1207, in join    task.result()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 737, in run_fetch_blocks    await self._process_header_at_tip()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 751, in _process_header_at_tip    _, height = await self.step(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 795, in step    height, header, bad, bad_header = await self._search_headers_backwards(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 881, in _search_headers_backwards    while await iterate():  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 866, in iterate    header = await self.get_block_header(height, 'backward')  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 604, in get_block_header    res = await self.session.send_request('blockchain.block.header', [height], timeout=timeout)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 171, in send_request    response = await asyncio.wait_for(  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for    return fut.result()  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 540, in send_request    return await self._send_concurrent(message, future, 1)  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 512, in _send_concurrent    return await futureaiorpcx.jsonrpc.RPCError: (1, '-7240991 should be a non-negative integer')20220523T143552.048955Z |     INFO | network | connecting to electrum.mydomain.biz:50002:s as new interface20220523T143552.277450Z |     INFO | interface.[electrum.mydomain.biz:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']20220523T143552.333548Z |     INFO | interface.[electrum.mydomain.biz:50002] | set blockchain with height -120220523T143552.334190Z |     INFO | interface.[electrum.mydomain.biz:50002] | can't connect 724099120220523T143552.334687Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header 0 in mode backward20220523T143552.335706Z |     INFO | network | switching to electrum.mydomain.biz:50002:s20220523T143552.393364Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header -7240991 in mode backward20220523T143552.396873Z |     INFO | network | fee_histogram []20220523T143552.515824Z |  WARNING | interface.[electrum.mydomain.biz:50002] | disconnecting due to RPCError(1, '-7240991 should be a non-negative integer')20220523T143552.516450Z |    DEBUG | interface.[electrum.mydomain.biz:50002] | (disconnect) trace for RPCError(1, '-7240991 should be a non-negative integer')Traceback (most recent call last):  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 498, in wrapper_func    return await func(self, *args, **kwargs)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 521, in run    await self.open_session(ssl_context)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 667, in open_session    async with self.taskgroup as group:  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/curio.py\", line 297, in __aexit__    await self.join()  File \"/home/koray/electrum-wdc/electrum_wdc/util.py\", line 1207, in join    task.result()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 737, in run_fetch_blocks    await self._process_header_at_tip()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 751, in _process_header_at_tip    _, height = await self.step(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 795, in step    height, header, bad, bad_header = await self._search_headers_backwards(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 881, in _search_headers_backwards    while await iterate():  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 866, in iterate    header = await self.get_block_header(height, 'backward')  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 604, in get_block_header    res = await self.session.send_request('blockchain.block.header', [height], timeout=timeout)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 171, in send_request    response = await asyncio.wait_for(  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for    return fut.result()  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 540, in send_request    return await self._send_concurrent(message, future, 1)  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 512, in _send_concurrent    return await futureaiorpcx.jsonrpc.RPCError: (1, '-7240991 should be a non-negative integer')20220523T143553.390308Z |     INFO | network | connecting to electrum.mydomain.biz:50002:s as new interface20220523T143553.616538Z |     INFO | interface.[electrum.mydomain.biz:50002] | connection established. version: ['ElectrumX 1.16.0', '1.4']20220523T143553.672049Z |     INFO | interface.[electrum.mydomain.biz:50002] | set blockchain with height -120220523T143553.672866Z |     INFO | interface.[electrum.mydomain.biz:50002] | can't connect 724099120220523T143553.673495Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header 0 in mode backward20220523T143553.674737Z |     INFO | network | switching to electrum.mydomain.biz:50002:s20220523T143553.731810Z |     INFO | interface.[electrum.mydomain.biz:50002] | requesting block header -7240991 in mode backward20220523T143553.734345Z |     INFO | network | fee_histogram []20220523T143553.851536Z |  WARNING | interface.[electrum.mydomain.biz:50002] | disconnecting due to RPCError(1, '-7240991 should be a non-negative integer')20220523T143553.852210Z |    DEBUG | interface.[electrum.mydomain.biz:50002] | (disconnect) trace for RPCError(1, '-7240991 should be a non-negative integer')Traceback (most recent call last):  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 498, in wrapper_func    return await func(self, *args, **kwargs)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 521, in run    await self.open_session(ssl_context)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 667, in open_session    async with self.taskgroup as group:  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/curio.py\", line 297, in __aexit__    await self.join()  File \"/home/koray/electrum-wdc/electrum_wdc/util.py\", line 1207, in join    task.result()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 737, in run_fetch_blocks    await self._process_header_at_tip()  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 751, in _process_header_at_tip    _, height = await self.step(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 795, in step    height, header, bad, bad_header = await self._search_headers_backwards(height, header)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 881, in _search_headers_backwards    while await iterate():  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 866, in iterate    header = await self.get_block_header(height, 'backward')  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 604, in get_block_header    res = await self.session.send_request('blockchain.block.header', [height], timeout=timeout)  File \"/home/koray/electrum-wdc/electrum_wdc/interface.py\", line 171, in send_request    response = await asyncio.wait_for(  File \"/usr/lib/python3.10/asyncio/tasks.py\", line 445, in wait_for    return fut.result()  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 540, in send_request    return await self._send_concurrent(message, future, 1)  File \"/home/koray/.local/lib/python3.10/site-packages/aiorpcx/session.py\", line 512, in _send_concurrent    return await futureaiorpcx.jsonrpc.RPCError: (1, '-7240991 should be a non-negative integer')20220523T143554.587536Z |     INFO | gui.qt.main_window.[default] | close_wallet /home/koray/.electrum-wdc/wallets/default20220523T143554.597515Z |     INFO | storage.WalletStorage | saved /home/koray/.electrum-wdc/wallets/default20220523T143554.597919Z |    DEBUG | util.profiler | WalletDB._write 0.007220220523T143554.602734Z |     INFO | daemon.Daemon | stop() entered. initiating shutdown20220523T143554.603018Z |     INFO | gui.qt.ElectrumGui | closing GUI20220523T143554.603249Z |     INFO | daemon.Daemon | stopping all wallets20220523T143554.603499Z |     INFO | daemon.Daemon | stopping network and taskgroup20220523T143554.603909Z |     INFO | network | stopping network20220523T143554.604650Z |     INFO | daemon.Daemon | taskgroup stopped.20220523T143554.604964Z |     INFO | network | taskgroup stopped (0x7fd672b33040).20220523T143554.605538Z |     INFO | daemon.Daemon | removing lockfile20220523T143554.605880Z |     INFO | daemon.Daemon | stopped20220523T143554.707466Z |     INFO | plugin.Plugins | stopped",
  "score": 0,
  "upvotes": 0,
  "downvotes": 0,
  "url": "https://bitcointalk.org/index.php?topic=5399888",
  "comments": [
    {
      "author": "DireWolfM14",
      "created_time": "May 23, 2022, 07:57:00 PM",
      "body": "Sorry, I have no experience with the coin in question, but this looks funny to me.Quote from: solayagim on May 23, 2022, 07:21:49 PMworldcoin.conf:Code:listen=1server=1txindex=1rpcuser=worldcoinrpcpassword=worldcoinrpcallowip=0.0.0.0/0rpcbind=0.0.0.0addnode=....Try removing rpcallowip, or comment it out by starting the line with a hashtag (#) like this:Code:#rpcallowip=0.0.0.0/0And for rpcbind try pointing that to localhost or 127.0.0.1, like this:Code:rpcbind=127.0.0.1orCode:rpcbind=localhost",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "NotATether",
      "created_time": "May 24, 2022, 05:27:43 AM",
      "body": "Remove the \"/0\" from the end of rpcallowip and add a whitebind directive for a whitelisted port and address you want ElectrumX to connect to, like this:Code:#bitcoin.conf # or whatever coin's .conf file you are usingwhitebind=127.0.0.1:8332This will allow RPC connections that connect to this IP and port without giving an \"Authentication error\". Note that this will only work if the RPC error you are getting is an authentication error. If it is not, then describe the error you are getting clearly.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "DireWolfM14",
      "created_time": "May 26, 2022, 02:56:08 PM",
      "body": "It's been a while since I've messed around with my node setup, but there's something I forgot:This:Code:rpcuser=worldcoinrpcpassword=worldcoinDoesn't belong in the worldcoin.conf file, it belongs in electrumx.conf.Here's the documentation for rpcauth.py from the bitcoin core master:Quote from: https://github.com/bitcoin/bitcoin/tree/master/share/rpcauthusage: rpcauth.py [-h] username [password]Create login credentials for a JSON-RPC userpositional arguments:  username    the username for authentication  password    leave empty to generate a random password or specify \"-\" to              prompt for passwordoptional arguments:  -h, --help  show this help message and exitSo, you'll need to use rpcauth.py to generate the authorization code that needs to be in the coin daemon's configuration file.  For example:As in the example above, if you use \"worldcoin\" as the rpc username and password (I suggest a stronger password, or let rpcauth.py generate one for you) you'll need the following code in your worldcoin.conf file:Code:rpcauth=worldcoin:1667bd1179bbdd121aec27fc98bb66e9$77cb74246ed721086f2b80cf32d76ffc63036dea38ae87794de662bc44155b83",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    }
  ]
}