{
  "id": "topic_5475505",
  "title": "francisOPL",
  "author": "francisOPL",
  "created_time": "November 25, 2023, 07:03:52 PM",
  "content": "I hope that this is not answered somewhere else -- if so, kindly post a link to the solution if known.  Otherwise here goes....So I'm on macOS Sonoma 14.1.1 (23B81) M1 and I got an older version of Armory to load on my machine.  (v95 -- I know it's an old one but it's the only one for which all dependencies seemed to be met) I had messed with everything on an old Ubuntu machine and I still will be intermittently if I can't get things up and running on my Mac. It seems way closer on the Mac at this point.I have encountered the \"stuck in offline mode\" related posts across the forum but so far nothing I have tried has worked.@goatpig if this is a fools errand please let me know.  I know that the wallet restores properly so all I need is to get bitcoin-core on my Ubuntu machine (already done, it's syncing currently) and go at it from that direction that's cool too.  I just prefer working with everything tangential to finances on one machine. Anyway it looks like my synced bitcoin-core-25.1 is not linking over into Armory properly... somehow... Here is my big ugly log file:These two are recurrent segments in the log\"\"\"2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1137 - C++ block utilities loaded successfully2023-11-24 19:57 (INFO) -- ArmoryUtils.py:651 - Executing popen: sysctl hw.memsize2023-11-24 19:57 (INFO) -- ArmoryUtils.py:651 - Executing popen: sysctl -n machdep.cpu.brand_string2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1247 - 2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1248 - 2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1249 - 2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1250 - ************************************************************2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1251 - Invoked: /Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ArmoryQt.py2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1252 - ************************************************************2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1253 - Loading Armory Engine:2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1254 -    Armory Version        : 0.95.12023-11-24 19:57 (INFO) -- ArmoryUtils.py:1255 -    Armory Build:         : None2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1256 -    PyBtcWallet  Version  : 1.352023-11-24 19:57 (INFO) -- ArmoryUtils.py:1257 - Detected Operating system: MacOSX2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1258 -    OS Variant            : 10.162023-11-24 19:57 (INFO) -- ArmoryUtils.py:1259 -    User home-directory   : /Users/USERNAME/Library/Application Support2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1260 -    Satoshi BTC directory : /Users/USERNAME/Library/Application Support/Bitcoin/2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1261 -    Armory home dir       : /Users/USERNAME/Library/Application Support/Armory/2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1262 - Detected System Specs    : 2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1263 -    Total Available RAM   : 16.00 GB2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1264 -    CPU ID string         : Apple M1 Pro2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1265 -    Number of CPU cores   : 10 cores2023-11-24 19:57 (INFO) -- ArmoryUtils.py:1266 -    System is 64-bit      : True2023-11-24 19:57 (ERROR) -- Traceback (most recent call last):  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ArmoryQt.py\", line 44, in <module>    from armoryengine.ALL import *  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/ALL.py\", line 8, in <module>    from armoryengine.ArmoryUtils import *  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/ArmoryUtils.py\", line 1267, in <module>    LOGINFO('   Preferred Encoding    : ' + locale.getpreferredencoding())TypeError: cannot concatenate 'str' and 'NoneType' objects\"\"\"and\"\"\"2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1204 -    Number of CPU cores   : 10 cores2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1205 -    System is 64-bit      : True2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1206 -    Preferred Encoding    : US-ASCII2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1207 -    Machine Arch          : x86_642023-11-24 21:44 (INFO) -- ArmoryUtils.py:1208 -    Available HDD (ARM)   : 12 GB2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1209 -    Available HDD (BTC)   : 12 GB2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1210 - 2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1211 - Network Name: Main Network2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1212 - Satoshi Port: 83332023-11-24 21:44 (INFO) -- ArmoryUtils.py:1213 - Do wlt check: True2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1214 - Named options/arguments to armoryengine.py:2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     nettimeout      : 22023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     rescan          : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     ignoreAllZC     : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     enableSupernode : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     disableModules  : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     port            : None2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     interport       : 82232023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     skipStatsReport : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     forceWalletCheck: False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     rebuild         : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     datadir         : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     clearMempool    : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     offline         : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     coverageOutputDir: None2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     armoryDBDir     : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     psn             : None2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     satoshiPort     : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     useTorSettings  : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     netlog          : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     keypool         : 1002023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     coverageInclude : None2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     forceOnline     : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     skipAnnounceCheck: False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     redownload      : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     multisigFile    : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     disableTorrent  : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     testAnnounceCode: False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     mtdebug         : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     logDisable      : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     settingsPath    : /Users/USERNAME/Library/Application Support/Armory/ArmorySettings.txt2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     verbosity       : None2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     doDebug         : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     enableDetSign   : True2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     testnet         : False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     rpcport         : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     satoshiHome     : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     satoshiRpcport  : DEFAULT2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     logFile         : /Users/USERNAME/Library/Application Support/Armory/ArmoryQt.py.log.txt2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1216 -     disableConfPermis: False2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1217 - Other arguments:2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1220 - ************************************************************2023-11-24 21:44 (INFO) -- ArmoryUtils.py:1620 - C++ block utilities loaded successfully2023-11-24 21:44 (INFO) -- BDM.py:418 - Using the asynchronous/multi-threaded BlockDataManager.2023-11-24 21:44 (INFO) -- BDM.py:419 - Blockchain operations will happen in the background.  2023-11-24 21:44 (INFO) -- BDM.py:420 - Devs: check TheBDM.getState() before asking for data.2023-11-24 21:44 (INFO) -- BDM.py:421 - Registering addresses during rescans will queue them for 2023-11-24 21:44 (INFO) -- BDM.py:422 - inclusion after the current scan is completed.2023-11-24 21:44 (INFO) -- ArmoryUtils.py:3531 - Using settings file: /Users/USERNAME/Library/Application Support/Armory/ArmorySettings.txt2023-11-24 21:44 (INFO) -- announcefetch.py:95 - Reading files in fetcher directory:2023-11-24 21:44 (INFO) -- announcefetch.py:271 - Fetching: https://bitcoinarmory.com/announce.txt?osvar=%28%2710.16%27%2C+%28%27%27%2C+%27%27%2C+%27%27%29%2C+%27x86_64%27%29&os=mac&ver=0.93.3&id=9ee7a4392023-11-24 21:44 (INFO) -- ArmoryQt.py:2736 - loadWalletsAndSettings2023-11-24 21:44 (INFO) -- ArmoryQt.py:2790 - Loading wallets...2023-11-24 21:44 (INFO) -- ArmoryQt.py:2849 - Number of wallets read in: 02023-11-24 21:44 (ERROR) -- announcefetch.py:283 - Specified URL was inaccessible2023-11-24 21:44 (ERROR) -- announcefetch.py:284 - Tried: https://bitcoinarmory.com/announce.txt?osvar=%28%2710.16%27%2C+%28%27%27%2C+%27%27%2C+%27%27%29%2C+%27x86_64%27%29&os=mac&ver=0.93.3&id=9ee7a4392023-11-24 21:44 (INFO) -- announcefetch.py:271 - Fetching: https://s3.amazonaws.com/bitcoinarmory-media/announce.txt2023-11-24 21:44 (ERROR) -- announcefetch.py:283 - Specified URL was inaccessible2023-11-24 21:44 (ERROR) -- announcefetch.py:284 - Tried: https://s3.amazonaws.com/bitcoinarmory-media/announce.txt2023-11-24 21:44 (WARNING) -- announcefetch.py:297 - Error fetching announce digest2023-11-24 21:44 (INFO) -- ArmoryQt.py:2298 - Setting up networking...2023-11-24 21:44 (INFO) -- ArmoryQt.py:2327 - Internet status: 02023-11-24 21:44 (INFO) -- ArmoryQt.py:2525 - loadBlockchainIfNecessary2023-11-24 21:44 (INFO) -- ArmoryQt.py:2546 - Setting netmode: 12023-11-24 21:44 (ERROR) -- BDM.py:324 - Blockchain data not available: /Users/USERNAME/Library/Application Support/Bitcoin/blocks/blk00000.dat2023-11-24 21:44 (ERROR) -- Traceback (most recent call last):  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ArmoryQt.py\", line 7147, in <module>    form = ArmoryMainWindow(splashScreen=SPLASH)  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ArmoryQt.py\", line 260, in __init__    self.loadBlockchainIfNecessary()  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/ArmoryQt.py\", line 2538, in loadBlockchainIfNecessary    TheBDM.goOnline()  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/BDM.py\", line 148, in inner    return func(*newArgs, **kwargs)  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/BDM.py\", line 251, in goOnline    self.bdmThread.setConfig(self.bdmConfig())  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/BDM.py\", line 148, in inner    return func(*newArgs, **kwargs)  File \"/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory/armoryengine/BDM.py\", line 325, in bdmConfig    raise FileExistsError, ('Blockchain data not available: %s' % blk1st)FileExistsError: Blockchain data not available: /Users/USERNAME/Library/Application Support/Bitcoin/blocks/blk00000.dat\"\"\"Peace 'n' Love,Francicso",
  "score": 0,
  "upvotes": 0,
  "downvotes": 0,
  "url": "https://bitcointalk.org/index.php?topic=5475505",
  "comments": [
    {
      "author": "goatpig",
      "created_time": "November 26, 2023, 10:27:44 AM",
      "body": "It cannot find your blockchain data. Are you using a custom Core folder? Is it running in pruned mode?",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "November 26, 2023, 10:07:21 PM",
      "body": "Bitcoin-core data is all being stored in the following folders it looks like:/Users/USERNAME/Library/Application Support/Bitcoin/Users/USERNAME/Library/Application Support/Bitcoin/blocksI don't know what pruned mode is... I'll look for def on the forum though.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "hosemary",
      "created_time": "November 27, 2023, 06:29:30 AM",
      "body": "Quote from: francisOPL on November 26, 2023, 10:07:21 PMI don't know what pruned mode is... I'll look for def on the forum though.In pruned mode, you don't store the full blockchain and you only store the UTXO set and the last x GB of blocks.To check if you are running a prune node, click on \"Setting\" at top of the window an then go to \"Options\". If you are running a prune node, you should uncheck \"Prune block storage to\" option and redownload the blockchain.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "November 27, 2023, 07:11:28 PM",
      "body": "@hosseinimr93 got it, yes it was pruned unfortunately... redownloading the blockchain now.@goatpig, so yep it was in pruned mode...",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "November 28, 2023, 08:07:21 AM",
      "body": "Quote from: francisOPL on November 27, 2023, 07:11:28 PM@hosseinimr93 got it, yes it was pruned unfortunately... redownloading the blockchain now.@goatpig, so yep it was in pruned mode...Unfortunately Armory cannot run against pruned nodes at the moment.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 10, 2023, 03:42:40 AM",
      "body": "Okay so I have everything nominally up and running...Here is my \"armorylog.txt\"Code:Traceback (most recent call last):  File \"/usr/local/bin/../lib/armory/ArmoryQt.py\", line 1835, in startBitcoindIfNecessary    TheSDM.setupSDM(extraExeSearch=self.satoshiExeSearchPath)  File \"/usr/local/lib/armory/SDM.py\", line 188, in setupSDM    if self.failedFindExe:  raise self.BitcoindError, 'bitcoind not found'BitcoindError: bitcoind not found2023-12-09 22:34 (INFO) -- ArmoryQt.py:1900 - Setting netmode: 02023-12-09 22:34 (INFO) -- ArmoryQt.py:1850 - setSatoshiPaths2023-12-09 22:34 (INFO) -- ArmoryQt.py:1868 - Setting satoshi datadir = /home/USERNAME/snap/bitcoin-core/common/.bitcoin/blocks2023-12-09 22:34 (ERROR) -- ArmoryQt.py:1808 - Failed to start Armory database: Invalid blockdata pathTraceback (most recent call last):  File \"/usr/local/bin/../lib/armory/ArmoryQt.py\", line 1793, in startArmoryDBIfNecessary    TheSDM.spawnDB(ARMORY_HOME_DIR, TheBDM.armoryDBDir)  File \"/usr/local/lib/armory/SDM.py\", line 368, in spawnDB    raise self.BadPath, \"Invalid blockdata path\"BadPath: Invalid blockdata path2023-12-09 22:34 (INFO) -- ArmoryQt.py:1900 - Setting netmode: 0I recall reading about bitcoinind somewhere in the forums but I don't remember where...  Sorry for my complete amateur mistake but I cannot for the life of me figure out what I need to do from here... Bitcoin-core needs to be running in the background right or is that a thing of the past?",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "December 10, 2023, 09:18:06 AM",
      "body": "Quoteif self.failedFindExe:  raise self.BitcoindError, 'bitcoind not found'It cannot find bitcoind, turn off auto bitcoin management in Armory (first page in File -> Settings) and run bitcoind manually. Probably this is because you installed bitcoin via snapQuote/home/USERNAME/snap/bitcoin-core/common/.bitcoin/blocksThis looks wrong. Your blockchain data should be in ~/.bitcoin. This is the folder path you should give it. Try the following:- From the terminal, cd to the Armory install folder: /usr/local/lib/armory- Run the db process on its own like this: ./ArmoryDB --satoshi-datadir=/home/*USERNAME*/.bitcoin- If it starts building the database, let it go all the way. Once it's done, start ArmoryQt.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 10, 2023, 03:49:38 PM",
      "body": "Yes I installed via snap.   I'll try again first with what you have suggested @goatpig.  Thank you.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 10, 2023, 04:49:07 PM",
      "body": "Hi @goatpig, when I tried your suggestion, \"./ArmoryDB --satoshi-datadir=/home/*USERNAME*/.bitcoin\" the only option that comes up is ./ArmoryQt.py.  I tried that though instead but then got:Code:Directory \"/home/*/.bitcoin\" does not exist!  Using default!(ERROR) ArmoryUtils.py:1236 - Error getting system details:Traceback (most recent call last):  File \"/usr/local/lib/armory/armoryengine/ArmoryUtils.py\", line 1234, in <module>    SystemSpecs = GetSystemDetails()  File \"/usr/local/lib/armory/armoryengine/ArmoryUtils.py\", line 1229, in GetSystemDetails    out.HddAvailB = getHddSize(BTC_HOME_DIR)    / (1024**3)  File \"/usr/local/lib/armory/armoryengine/ArmoryUtils.py\", line 1226, in getHddSize    s = os.statvfs(adir)OSError: [Errno 2] No such file or directory: '/home/*USERNAME*/.bitcoin/'(ERROR) ArmoryUtils.py:1237 - Skipping.(ERROR) ArmoryUtils.py:3747 - Unsupported language  specified. Defaulting to English (en)/usr/local/lib/armory/armoryengine/Transaction.py:2790: SyntaxWarning: import * only allowed at module level  def PyCreateAndSignTx_old(srcTxOuts, dstAddrsVals):No systemtrayicon available(ERROR) BDM.py:275 - setSatoshiDir: directory does not exist: /home/*USERNAME*/.bitcoin/(ERROR) ArmoryQt.py:1840 - Failed to setup SDMTraceback (most recent call last):  File \"./ArmoryQt.py\", line 1835, in startBitcoindIfNecessary    TheSDM.setupSDM(extraExeSearch=self.satoshiExeSearchPath)  File \"/usr/local/lib/armory/SDM.py\", line 188, in setupSDM    if self.failedFindExe:  raise self.BitcoindError, 'bitcoind not found'BitcoindError: bitcoind not found(ERROR) BDM.py:275 - setSatoshiDir: directory does not exist: /home/*USERNAME*/.bitcoin/(ERROR) ArmoryQt.py:1808 - Failed to start Armory database: Invalid blockdata pathTraceback (most recent call last):  File \"./ArmoryQt.py\", line 1793, in startArmoryDBIfNecessary    TheSDM.spawnDB(ARMORY_HOME_DIR, TheBDM.armoryDBDir)  File \"/usr/local/lib/armory/SDM.py\", line 368, in spawnDB    raise self.BadPath, \"Invalid blockdata path\"It looks like all the path issues with snap are the problem...  From here, as it stands though what could I try next?  Should I go ahead and wipe bitcoin-core off my machine and install it from the official tgz and start fresh?Looking forward to getting this handled. Thanks so much @goatpig",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "December 11, 2023, 07:52:52 AM",
      "body": "QuoteHi @goatpig, when I tried your suggestion, \"./ArmoryDB --satoshi-datadir=/home/*USERNAME*/.bitcoin\" the only option that comes up is ./ArmoryQt.pyYou have to cd to the folder where the binary is installed first. I honestly don't remember where it goes on Ubuntu. I'm guessing /usr/local/bin or /usr/local/lib/Armory. Try \"whereis ArmoryDB\" or cd to /usr and \"find . ArmoryDB\".QuoteIt looks like all the path issues with snap are the problem...  From here, as it stands though what could I try next?  When you start BitcoinQt, what does it show you? I believe it can display where the blockchain data is located. Do you have a ./bitcoin folder in your home folder? You need to find where Core downloaded the blockchain data and feed that to Armory. If you find it and Armory can't read it, then it's a permission issue. We can look at that too.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "December 11, 2023, 07:54:13 AM",
      "body": "Quote from: goatpig on December 11, 2023, 07:52:52 AMQuoteHi @goatpig, when I tried your suggestion, \"./ArmoryDB --satoshi-datadir=/home/*USERNAME*/.bitcoin\" the only option that comes up is ./ArmoryQt.pyYou have to cd to the folder where the binary is installed first. I honestly don't remember where it goes on Ubuntu. I'm guessing /usr/local/bin or /usr/local/lib/Armory. Try \"whereis ArmoryDB\" or cd to /usr and \"find . ArmoryDB\".QuoteIt looks like all the path issues with snap are the problem...  From here, as it stands though what could I try next?  When you start BitcoinQt, what does it show you? I believe it can display where the blockchain data is located. Do you have a ./bitcoin folder in your home folder? You need to find where Core downloaded the blockchain data and feed that to Armory. If you find it and Armory can't read it, then it's a permission issue. We can look at that too.QuoteShould I go ahead and wipe bitcoin-core off my machine and install it from the official tgz and start fresh?I don't think that's necessary. The data is somewhere on your system, just need to find it. Hell, you could look at folder sizes and figure it out that way. Some 400GB of data doesn't just sneak around on a disk.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 12, 2023, 12:33:11 AM",
      "body": "Yes in BitcoinQt here are the Datadir and Blocksdir, respectively:/home/*USERNAME*/snap/bitcoin-core/common/.bitcoin/home/*USERNAME*/snap/bitcoin-core/common/.bitcoin/blocksOkay I got ArmoryDB and tried that same command: ./ArmoryDB --satoshi-datadir=/home/*USERNAME*/snap/bitcoin-core/common/.bitcoinSeems to be working on the db right now... so not a permissions issue...Will check back in a few hours once it's all done.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 12, 2023, 02:59:58 AM",
      "body": "It finished, here's the output:-DEBUG - 1702343930: (Blockchain.cpp:242) Organizing chain -INFO  - 1702343939: (DatabaseBuilder.cpp:56) updated HEADERS db in 8045.85s-INFO  - 1702343939: (BlockUtils.cpp:1206) Enabling zero-conf tracking Now I did everything else... lol 0.0000 BTC balance...  No idea...",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "December 12, 2023, 08:50:07 AM",
      "body": "Quote from: francisOPL on December 12, 2023, 02:59:58 AMIt finished, here's the output:-DEBUG - 1702343930: (Blockchain.cpp:242) Organizing chain -INFO  - 1702343939: (DatabaseBuilder.cpp:56) updated HEADERS db in 8045.85s-INFO  - 1702343939: (BlockUtils.cpp:1206) Enabling zero-conf tracking Now I did everything else... lol 0.0000 BTC balance...  No idea... ArmoryDB isn't aware of your wallets until you start ArmoryQt. The step you did was to get ArmoryDB to chain data and prepare its db. It now needs to be fed your addresses by ArmoryQt to scan them. You should see a bunch of scanning info in the ArmoryDB output as you start ArmoryQt. Is it not scanning?",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 12, 2023, 01:39:42 PM",
      "body": "Yes I started ArmoryQt.  It's scanning but has been stuck overnight at 31%.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 12, 2023, 11:44:39 PM",
      "body": "Everything restored after a few iterations of forcing the db to rebuild.All Hail @GoatPigThanks bruv",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "goatpig",
      "created_time": "December 13, 2023, 07:15:02 AM",
      "body": "I'll fix this crap one day, I swear",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    },
    {
      "author": "francisOPL",
      "created_time": "December 15, 2023, 09:52:03 PM",
      "body": "Haha no worries @goatpig.  You helped a bunch.",
      "score": 0,
      "upvotes": 0,
      "downvotes": 0
    }
  ]
}